version: "2.1"
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: postgres
    ports:
      - "5431:5432"