version: "2.1"
services:
  # mysql:
  #   image: arm64v8/mysql:8
  #   restart: always
  #   # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
  #   # (this is just an example, not intended to be a production configuration)
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example
  #     MYSQL_USER: docker
  #     MYSQL_PASSWORD: docker
  #     MYSQL_DATABASE: apiworld
  #   ports:
  #     - "3306:3306"
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: postgres
    ports:
      - "5431:5432"
  # Could also use https://github.com/balena-io/open-balena-s3
  minio-server:
    image: quay.io/minio/minio
    restart: always
    environment:
      MINIO_ROOT_USER: AKIAIOSFODNN7EXAMPLE
      MINIO_ROOT_PASSWORD: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server /data --console-address ":9001"
    ports:
      - "43680:9000"
      - "43697:9001"
  minio-client:
    image: minio/mc
    depends_on:
      - minio-server
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add minio-server http://minio-server:9000 AKIAIOSFODNN7EXAMPLE wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY;
      /usr/bin/mc mb --ignore-existing minio-server/balena-pine-web-resources;
      /usr/bin/mc anonymous set download minio-server/balena-pine-web-resources;
      exit 0;
      "

